### ISSUE TITLE
Cannot start a simple application

### ISSUE THREAD

**Issue by charlesfleche** [sloria/aiohttp_utils#2]
This simple application fails to run with `aiohttp_utils.run`:

``` python
from aiohttp import web
from aiohttp_utils import run

async def handle(request):
    text = 'Hello World'
    return web.Response(body=text.encode('utf-8'))

app = web.Application()
app.router.add_route('GET', '/', handle)

if __name__ == '__main__':
    run(app,
        app_uri='mymodule:app',
        reload=True,
        port=5000)
```

Spawing the worker fails with this error:

``` python
Traceback (most recent call last):
  File "/home/charles/src/github/charles/asynctests/env35/lib/python3.5/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/home/charles/src/github/charles/asynctests/env35/lib/python3.5/site-packages/aiohttp/worker.py", line 30, in init_process
    super().init_process()
  File "/home/charles/src/github/charles/asynctests/env35/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.run()
  File "/home/charles/src/github/charles/asynctests/env35/lib/python3.5/site-packages/aiohttp/worker.py", line 36, in run
    self.loop.run_until_complete(self._runner)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 343, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/charles/src/github/charles/asynctests/env35/lib/python3.5/site-packages/aiohttp/worker.py", line 85, in _run
    handler = self.make_handler(self.wsgi)
TypeError: make_handler() missing 2 required positional arguments: 'host' and 'port'
```

- aiohttp 0.21.5
- aiohttp_utils 2.0.0
- python 3.5.0+ on kubuntu 15.10

**Comment by sloria** [comment]
I was able to reproduce this. I will release a fix for this shortly.

**Comment by charlesfleche** [comment]
That was fast ! Many thanks.
